name: Flutter Web Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone Flutter action repo
      - name: Clone repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Show flutter version
      - run: flutter --version

      # Install Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # Analizing the project
      - name: Analyze project
        run: flutter analyze

      # Build web project
      - name: Build web project
        run: flutter build web
